pos/api/urls.py
from django.urls import path
from .views import ProductsListApiView,ProductsUpdateView


app_name = "api"


urlpatterns = [
    path("products/", ProductsListApiView.as_view(), name="products"),
    path("products/update/<int:pk>", ProductsUpdateView.as_view(), name="products-update")
    ]

pos/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_select2 import urls as select2_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="products")),
    path("auth/", include("authentication.urls", namespace="authentication")),
    path("select2/", include(select2_urls), name="select2"),
]


urlpatterns += [path("api/", include("api.urls", namespace="api"))]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    

pos/product/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import urlencode
from django.urls import re_path


app_name = "products"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    # ? products
    path("product-list", views.ProductList.as_view(), name="product_list"),
    path("add-product", views.addproduct, name="add_product"),
    path("add_single_product", views.add_single_product, name="add_single_product"),
    path("upload_products", views.upload_products, name="upload_products"),
    path("list-category", views.list_category, name="list_category"),
    path("add_product_upload", views.add_product_upload, name="add_product_upload"),
    path("add-category", views.AddCategory, name="add_category"),
    # sales
    path("add_sales", views.AddSale.as_view(), name="add_sales"),
    path("list_sales", views.ListSale.as_view(), name="list_sales"),
    path("product_search", views.AddSale.as_view(), name="product_search"),
    path("complete_sale", csrf_exempt(views.complete_sale), name="complete_sale"),
    #! purchases
    path("add_purchases", views.AddPurchase.as_view(), name="add_purchases"),
    path("list_purchases", views.ListPurchase.as_view(), name="list_purchases"),
    path("add_purchase_upload", views.add_purchase_upload, name="add_purchase_upload"),
    path(
        "generate_purchase_list",
        views.generate_purchase_list,
        name="generate_purchase_list",
    ),
    path("add_single_purchase", views.add_single_purchase, name="add_single_purchase"),
    path("add_single_sell", views.add_single_sell, name="add_single_sell"),
    path("upload_purchase", views.upload_purchase, name="upload_purchase"),
    #!report
    path("reports", views.reports, name="reports"),
    # utils
    path("generate_barcode", views.generate_barcode, name="generate_barcode"),
    path(
        "get_product_by_uuid/<str:uuid>",
        views.get_product_by_uuid,
        name="get_product_by_uuid",
    ),
    # export to excel
    path("export_to_excel", views.export_to_excel, name="export_to_excel"),
    path(
        "export_all_products_excel",
        views.export_all_products_excel,
        name="export_all_products_excel",
    ),
    path(
        "export_all_sales_excel",
        views.export_all_sales_excel,
        name="export_all_sales_excel",
    ),
    path(
        "get_single_product/<str:pk>/",
        views.get_single_product,
        name="update_product",
    ),path("daily_profit", views.daily_profit, name="daily_profit"),
    path("month_profit", views.get_month_profit, name="month_profit"),
]

# htmx

urlpatterns += [
    # path(
    #     "get_single_product/<str:pk>/",
    #     views.get_single_product,
    #     name="update_product",
    # ),
    re_path(
        "get_profit_for_single_date/<str:date>",
        views.get_profit_for_single_date,
        name="get_profit_for_date",
    ),
]

pos/product/views.py
from product.form import CategoryForm, AddProductForm, AddSalesForm, AddPurchaseForm
from datetime import datetime, date
import time
from authentication.models import CustomUser
from django.shortcuts import render, redirect, get_object_or_404
from .utils import generate_random_code
from product.models import *
from django.http import JsonResponse, HttpResponse
from .form import FileUploadForm
import pandas as pd
from django.views.decorators.csrf import csrf_exempt
import json
from django.db.models import DateTimeField
from django.db.models import (
    ExpressionWrapper,
    F,
    Func,
    Value,
    Sum,
    DateField,
    CharField,
    FloatField,
    DecimalField,
)
from django.db.models.functions import Trunc, Cast, TruncDate
from django.db.models import Q


from django.template.loader import render_to_string
from django.views import generic
from xhtml2pdf import pisa
from io import BytesIO
import re

import xlwt

# ???  decorator
from django.contrib.auth.decorators import login_required, user_passes_test

# openpyxl
from openpyxl import load_workbook
import uuid

# from barcode import Code128, Code39
# from barcode.writer import ImageWriter
import uuid
from django.conf import settings
import os
from django.db.models.functions import TruncMonth
from collections import defaultdict


def is_admin(user):
    print(user)
    return user.groups.filter(name="ADMIN").exists()


@login_required
def dashboard(request):
    # get the value of all your store products at cost price
    total_cost = Products.objects.aggregate(
        total_cost=Sum(F("unit_price") * F("quantity_in_stock"))
    )["total_cost"]
    # formatted_total_cost = '{:,.0f}'.format(total_cost)
    total_cost_at_selling_price = Products.objects.aggregate(
        total_cost=Sum(F("cost") * F("quantity_in_stock"))
    )["total_cost"]
    total_cost_of_sales = Sales.objects.aggregate(total_cost=Sum(F("total")))[
        "total_cost"
    ]

    total_stock_cost = (
        Products.objects.filter(stock_take_done=True)
        .annotate(new__stock=Cast("new_stock", FloatField()))
        .aggregate(purchase_cost=Sum(F("unit_price") * F(("quantity_in_stock"))))
    )
    print(total_stock_cost)
    total_no_of_products = Products.objects.all().count()
    total_no_of_sales = Sales.objects.all().count()
    # sales_of_yesterday = Sales.objects.filter(
    #     date_sold__date=datetime.date.today() - datetime.timedelta(days=1)
    # ).aggregate(total_sales=Sum(F("total")))["total_sales"]
    sales_of_yesterday = Sales.objects.filter(
        date_sold__exact=datetime.date.today() - datetime.timedelta(days=1)
    ).aggregate(total_sales=Sum(F("total")))["total_sales"]

    # todays sales

    sales_of_today = Sales.objects.filter(
        date_sold__exact=datetime.date.today()
    ).aggregate(total_sales=Sum(F("total")))["total_sales"]

    # ? top selling products
    top_selling_products = Products.objects.annotate(
        total_quantity_sold=Sum("sales__quantity")
    ).order_by("-total_quantity_sold")[:5]
    print(top_selling_products)

    # value_if_true if condition else value_if_false
    total_sales_of_yesterday = sales_of_yesterday if sales_of_yesterday else 0
    total_sales_of_today = sales_of_today if sales_of_today else 0
    if total_cost_of_sales is not None:
        formatted_total_cost_of_sales = format(int(total_cost_of_sales), ",d")
    else:
        formatted_total_cost_of_sales = 0

    if total_cost is not None:
        formatted_total_cost = format(int(total_cost), ",d")
    else:
        formatted_total_cost = 0

    if total_cost_at_selling_price is not None:
        foramtted_total_cost_at_selling_price = format(
            int(total_cost_at_selling_price), ",d"
        )
    else:
        foramtted_total_cost_at_selling_price = 0

    context = {
        "total_cost": formatted_total_cost,
        "total_cost_at_selling_price": foramtted_total_cost_at_selling_price,
        "total_sales_of_yesterday": format(int(total_sales_of_yesterday), ",d"),
        "total_sales_of_today": format(int(total_sales_of_today), ",d"),
        "total_no_of_products": total_no_of_products,
        "total_no_of_sales": total_no_of_sales,
        "total_cost_of_sales": formatted_total_cost_of_sales,
        "top_selling_products": top_selling_products,
        "total_stock_cost": format(int(total_stock_cost["purchase_cost"]), ",d"),
    }
    return render(request, "dashboard/dashboard.html", context)


# ?------------------------------------ADD PRODUCT ----------------------------
class AddProduct(generic.TemplateView):
    template_name = "products/add_products.html"


class ProductList(generic.View):
    template_name = "products/products_list.html"
    model = Products
    context_object_name = "products"
    ordering = ["created_at"]

    #  product form
    def get(self, request, *args, **kwargs):
        products = self.model.objects.all()
        products_form = AddProductForm()
        context = {"products": products, "products_form": products_form}
        return render(request, self.template_name, context)

    # def post(self, request, *args, **kwargs ):


def get_single_product(request, pk):
    # if request.method == "GET"
    prod_id = str(pk)
    print(prod_id)

    # Assuming 'id' is the field in your Products model that you want to filter on
    product = get_object_or_404(Products, id=prod_id)
    product_data = {
        "product_name": product.product_name,
        "unit_price": product.unit_price,
        "cost": product.cost,
        "quantity_in_stock": product.quantity_in_stock,
        "new_stock": product.new_stock,
    }

    print(product_data)
    return JsonResponse(product_data)


@login_required
def addproduct(request):
    form = AddProductForm()
    uploadform = FileUploadForm()
    context = {"form": form, "uploadform": uploadform}

    return render(request, "products/add_products.html", context)


@login_required
def list_category(request):
    categories = Category.objects.all()
    context = {"categories": categories}

    return render(request, "categories/list_cat.html", context)


@login_required
def AddCategory(request):
    error = None
    if request.method == "POST":
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        else:
            error = form.errors
    else:
        form = CategoryForm()
    context = {"form": form, "error": error}
    return render(request, "categories/add_cat.html", context)


def add_single_product(request):
    if request.method == "POST":
        print(request.POST, request.FILES)
        product_name = request.POST["product_name"]
        category = request.POST["category_id"]
        cost_price = request.POST["unit_price"]
        selling_price = request.POST["cost"]
        quantity_in_stock = request.POST["quantity_in_stock"]
        brand_name = request.POST["brand"]
        unit_of_measure = request.POST.get("unit_of_measure", "pcs")
        reorder_level = request.POST.get("reorder_level", 0)
        description = request.POST.get("description", "none")
        # product_image = request.FILES["pic"]

        category = Category.objects.get(id=category)
        brand = Brand.objects.get(id=brand_name)
        # gererate product code

        product_code = generate_random_code(13)

        Products.objects.create(
            product_name=product_name,
            category_id=category,
            cost=selling_price,
            unit_price=cost_price,
            quantity_in_stock=quantity_in_stock,
            brand=brand,
            unit_of_measure=unit_of_measure,
            reorder_level=reorder_level,
            description=description,
            product_code=product_code,
            stock_take_done=True,
            # product_image=product_image,
        )
        return redirect("products:product_list")

    return render(request, "products/add_products.html")


# ? ------------------------------------- sales -------------------------------------


def add_single_sell(request):
    form = AddSalesForm
    if request.method == "POST":
        user = request.user
        data = request.POST
        data_sold = data["date_sold"]
        product_name = data["product_name"]
        product_uuid = data["product_uuid"]
        discount = data["discount"]
        quantity = int(data["quantity"])
        price = int(data["price"])
        product = Products.objects.get(product_code=product_uuid)
        product.stock_take_done = True
        total_price = (int(price) * int(quantity)) - int(discount)
        print(total_price, discount)
        Sales.objects.create(
            user=user,
            date_sold=data_sold,
            product=product,
            quantity=quantity,
            total=total_price,
            price=price,
            discount=discount,
        )
        return redirect("products:add_single_sell")

    return render(
        request,
        "sales/add_single_sell.html",
        {"form": form},
    )


class AddSale(generic.View):
    template_name = "sales/add_sales.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        #! if request.is_ajax and request.method == "POST":
        #! checkin if request is ajax
        # if request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest":
        name = request.POST.get("product")
        res = None

        # qs = Products.objects.filter(product_name__icontains=name or product_code__icontains=name)
        qs = Products.objects.filter(
            Q(product_name__icontains=name) | Q(product_code__icontains=name)
        )

        data = []
        print(qs)
        if len(qs) > 0 and len(name) > 0:
            for i in qs:
                item = {
                    "code": i.product_code,
                    "name": i.product_name,
                    "price": i.cost,

pos/templates/products/add_products.html
{% extends 'base/base.html' %} {% block content %} {% load widget_tweaks %}
<div class="content-page">
  <div class="container-fluid add-form-list">
    <div class="row">
      <!-- Extra large modal -->

      {% if products %}
     
     <div
     id="product_popup"
     class="modal fade bd-example-modal-xl show"
     tabindex="-1"
     role="dialog"
     aria-modal="true"
     style="padding-right: 4px; display: block"
   >
     <div class="modal-dialog modal-xl  modal-dialog-scrollable" role="document" id="exampleModalCenter">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title">Edit Uploaded data</h5>
           <button
           id="close_product_popup"
             type="button"
             class="close"
             data-dismiss="modal"
             aria-label="Close"
           >
             <span aria-hidden="true">×</span>
           </button>
         </div>
         <div class="modal-body">
          <div class="card">
           <form action="{% url 'products:add_product_upload' %}" method="post">
            {% csrf_token %}
            <div class="card-header">
              <button type="submit" class="btn btn-primary">Submit</button>

            </div>
            <div class="card-body">
               <table class="table">
                  <thead>
                     <tr>
                       <th scope="col">UUID</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Description</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Purchase Price</th>
                        <th scope="col">Sales Price</th>
                        <th scope="col">Category</th>
                        <th scope="col">Unit</th>
                        <th scope="col">Brand</th>
                     </tr>
                  </thead>
                  <tbody>
                  {% for product  in products %}
                    <tr class="table-default">
                      <th scope="row">
                        <input
                          type="text"
                          class="form-control"
                          name="uuid"
                          value="{{ product.uuid }}"
                          readonly
                        />
                      <th scope="row">
                        <input
                          type="text"
                          class="form-control"
                          name="product_name"
                          value="{{ product.product_name }}"
                        />
                      </th>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="description"
                          value="{{ product.description }}"
                        />
                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="quantity"
                          value="{{ product.quantity }}"
                        />

                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="purchase_price"
                          value="{{ product.purchase_price }}"
                        />

                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="sales_price"
                          value="{{ product.sales_price }}"
                        />

                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="category"
                          value="{{ product.category }}"
                        />

                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="unit"
                          value="{{ product.unit }}"
                        />

                      </td>
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          name="brand"
                          value="{{ product.brand }}"
                        />

                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
               </table>
             
            </div>
            </form>
         </div>
         </div>
        
       </div>
     </div>
   </div>
      {% endif %}

      <div class="header-title">
        <h4 class="card-title">Upload Execl File</h4>
      </div>
      <div class="input-group mb-4 mr-3 col-">
        <form
          class="d-flex"
          method="post"
          enctype="multipart/form-data"
          action="{% url 'products:upload_products' %}"
        >
          {% csrf_token %}
          <div class="custom-file">
            {% render_field uploadform.file class="custom-file-input" id="inputGroupFile04" required="required" %}
           
            <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
          </div>
          <div class="input-group-append">
            <button class="btn btn-outline-secondary ml-4" type="submit">
              Submit
            </button>
          </div>
        </form>
      </div>
      <div class="col-sm-12">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Add Product</h4>
            </div>
          </div>
          <div class="card-body">
            <form action="{% url 'products:add_single_product' %}" method="POST" data-toggle="validator" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="row">
                
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name *</label>

                    {{ form.product_name }}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
           
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Category *</label>
                   
                    {% render_field form.category_id  class="form-control" %}
                  </div>
                </div>
           
              
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Cost *</label>
                    {% render_field form.unit_price class="form-control" placeholder="Enter Cost" data-errors="Please Enter Cost."%}
                 
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Selling Price *</label>
                    {% render_field form.cost  class="form-control" placeholder="Enter Selling Price" data-errors="Please Enter Price." %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
             
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Quantity *</label>
                   
                    {% render_field form.quantity_in_stock  class="form-control" placeholder="Enter Quantity" data-errors="Please Enter Quantity." %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Brand *</label>
                    {% render_field form.brand class="form-control" %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Unit of Measure *</label>
                    {% render_field form.unit_of_measure class="form-control" %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Reorder level *</label>
                    {% render_field form.reorder_level class="form-control" %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
           
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Image</label>
                    {% comment %} <input
                      type="file"
                      class="form-control image-file"
                      name="pic"
                      accept="image/*"
                    /> {% endcomment %}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Supplier</label>
                    {% render_field form.supplier class="form-control" %}
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label>Description / Product Details</label>
                
                    {% render_field form.description  class="form-control" rows="4" %}
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary mr-2">
                Add Product
              </button>
              <button type="reset" class="btn btn-danger">Reset</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Page end  -->
  </div>
</div>

{% endblock content %}