pos/api/urls.py
from django.urls import path
from .views import ProductsListApiView,ProductsUpdateView


app_name = "api"


urlpatterns = [
    path("products/", ProductsListApiView.as_view(), name="products"),
    path("products/update/<int:pk>", ProductsUpdateView.as_view(), name="products-update")
    ]

pos/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_select2 import urls as select2_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="products")),
    path("auth/", include("authentication.urls", namespace="authentication")),
    path("select2/", include(select2_urls), name="select2"),
]


urlpatterns += [path("api/", include("api.urls", namespace="api"))]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    

pos/product/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import urlencode
from django.urls import re_path


app_name = "products"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    # ? products
    path("product-list", views.ProductList.as_view(), name="product_list"),
    path("add-product", views.addproduct, name="add_product"),
    path("add_single_product", views.add_single_product, name="add_single_product"),
    path("upload_products", views.upload_products, name="upload_products"),
    path("list-category", views.list_category, name="list_category"),
    path("add_product_upload", views.add_product_upload, name="add_product_upload"),
    path("add-category", views.AddCategory, name="add_category"),
    # sales
    path("add_sales", views.AddSale.as_view(), name="add_sales"),
    path("list_sales", views.ListSale.as_view(), name="list_sales"),
    path("product_search", views.AddSale.as_view(), name="product_search"),
    path("complete_sale", csrf_exempt(views.complete_sale), name="complete_sale"),
    #! purchases
    path("add_purchases", views.AddPurchase.as_view(), name="add_purchases"),
    path("list_purchases", views.ListPurchase.as_view(), name="list_purchases"),
    path("add_purchase_upload", views.add_purchase_upload, name="add_purchase_upload"),
    path(
        "generate_purchase_list",
        views.generate_purchase_list,
        name="generate_purchase_list",
    ),
    path("add_single_purchase", views.add_single_purchase, name="add_single_purchase"),
    path("add_single_sell", views.add_single_sell, name="add_single_sell"),
    path("upload_purchase", views.upload_purchase, name="upload_purchase"),
    #!report
    path("reports", views.reports, name="reports"),
    # utils
    path("generate_barcode", views.generate_barcode, name="generate_barcode"),
    path(
        "get_product_by_uuid/<str:uuid>",
        views.get_product_by_uuid,
        name="get_product_by_uuid",
    ),
    # export to excel
    path("export_to_excel", views.export_to_excel, name="export_to_excel"),
    path(
        "export_all_products_excel",
        views.export_all_products_excel,
        name="export_all_products_excel",
    ),
    path(
        "export_all_sales_excel",
        views.export_all_sales_excel,
        name="export_all_sales_excel",
    ),
    path(
        "get_single_product/<str:pk>/",
        views.get_single_product,
        name="update_product",
    ),path("daily_profit", views.daily_profit, name="daily_profit"),
    path("month_profit", views.get_month_profit, name="month_profit"),
]

# htmx

urlpatterns += [
    # path(
    #     "get_single_product/<str:pk>/",
    #     views.get_single_product,
    #     name="update_product",
    # ),
    re_path(
        "get_profit_for_single_date/<str:date>",
        views.get_profit_for_single_date,
        name="get_profit_for_date",
    ),
]

pos/templates/sales/add_sales.html
{% extends 'base/base.html' %} {% block content %}

<div class="wrapper">
  <div class="content-page">
    {% comment %}
    <div class="card">
      <div class="card-body">
        {% endcomment %} {% comment %}
        <p class="mb-1">Search For Product</p>
        {% endcomment %}
        <!-- Extra large modal -->
        <!-- Large modal -->

        <div
          class="d-flex"
          style="
            align-items: center;
            margin-bottom: 20px;
            width: 100%;
            justify-content: space-between;
          "
        >
          <button
            type="button"
            class="btn btn-primary mt-2 mb-4 ml-3"
            data-toggle="modal"
            data-target=".bd-example-modal-lg"
            id="searh_modal_popup"
          >
            Search for Product
          </button>
          <div class="d-flex align-items-center mb-3 ml-2">
            <h5 class="mr-2">Total Price :</h5>
            <h5>UGX</h5>
            <h4 class="ml-2" id="current_total_price">0</h4>
          </div>
          <button
            id="clear__cart"
            type="button"
            class="btn btn-primary float-right mt-2 mb-4 ml-6"
          >
            clear Cart
          </button>
        </div>
        <div
          class="modal fade bd-example-modal-lg"
          tabindex="-1"
          role="dialog"
          aria-hidden="true"
          id="product_popup_search"
        >
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <div class="iq-search-bar device-search">
                  <form action="#" class="searchbox">
                    {% csrf_token %}
                    <a class="search-link" href="#"
                      ><i class="ri-search-line"></i
                    ></a>
                    <input
                      type="text"
                      class="text search-input"
                      placeholder="Search here......"
                      id="search_product_by_name"
                    />
                  </form>
                </div>
                <button
                  type="button"
                  class="close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body container" id="results-box"></div>
              {% comment %}
              <div class="modal-footer">
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-dismiss="modal"
                >
                  Close
                </button>
                <button type="button" class="btn btn-primary">
                  Save changes
                </button>
              </div>
              {% endcomment %}
            </div>
          </div>
        </div>
        <div
          class="iq-search-bar device-search mb-4 ml-3 d-flex justify-content-lg-between"
        >
          <form action="#" class="searchbox">
            <a class="search-link" href="#"><i class="ri-search-line"></i></a>
            <input
              type="text"
              class="text search-input"
              placeholder="Search here..."
              id="search_product_uuid"
              autocomplete="off"
              onkeyup="formatNumber(this)"
            />
          </form>
          <form action="#" class="searchbox">
            <input
              type="text"
              class="text search-input w-50"
              placeholder="Amount Received"
              id="amount_received"
              autocomplete="off"
            />
          </form>
          <div class="d-flex align-items-center mb-3">
            <h5>Change:</h5>
            <h5 class="mr-1" id="change">UGX</h5>
            <h5 id="current_change">0</h5>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                {% comment %} style="display: none;" {% endcomment %}
                <table class="table" id="product__table">
                  <thead>
                    <tr>
                      {% comment %}
                      <th scope="col">#</th>
                      {% endcomment %}
                      <th scope="col">Product Name</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Price</th>
                      <th scope="col">Total Price</th>
                    </tr>
                  </thead>
                  <tbody id="product__table_body">
                    <tr>
                      {% comment %}
                      <th scope="row" id="product_count"></th>
                      <td id="product_uuid"></td>
                      <td id="product_name"></td>
                      {% endcomment %} {% comment %}
                      <td>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Quantity"
                          id="product_quantity"
                        />
                      </td>
                      {% endcomment %} {% comment %}
                      <td id="product_price"></td>
                      <td id="product_total_price"></td>
                      {% endcomment %}
                    </tr>
                  </tbody>
                </table>
              </div>
              <button
                type="button"
                class="btn btn-primary"
                id="submit__product"
                style="display: none"
                onclick="submit__product()"
              >
                Submit
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </div>
</div>

pos/templates/sales/add_single_sell.html
{% extends 'base/base.html' %} {% block content %} {% load widget_tweaks %}
<div class="content-page">
  <div class="container-fluid add-form-list">
    <div class="row">
      <div class="col-sm-12">
        <div class="card">
          <div class="card-header d-flex justify-content-between">
            <div class="header-title">
              <h4 class="card-title">Add Product</h4>
            </div>
          </div>
          <div class="card-body">
            <form method="POST" data-toggle="validator" action="{% url 'products:add_single_sell' %}">
              <div class="row">
          
                <div class="col-md-6">
                    <div class="form-group">
                      <label> Date * </label>
  
                  
                      {% render_field form.date_sold type="date" class="form-control"   %}

  
                      <div class="help-block with-errors"></div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                        <input
                      type="search"
                      class="form-control"
                      placeholder="Search Product"
                    
                      id="foreign_key_input"
                    />
                    <div class="modal-body container" id="results-box-single-sale"></div>
                    {% csrf_token %}
                    
                 
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <label>Code *</label>
  
                      <input
                      type="text"
                      class="form-control"
                      name = "product_uuid"
                      data-errors="Please Enter Cost."
                      id="product_code"
                      readonly
                    />
  
                      <div class="help-block with-errors"></div>
                    </div>
                  </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Name *</label>

                    <input
                    type="text"
                    class="form-control"
                    name="product_name"
                    data-errors="Please Enter Cost."
                    id="product_name"
                    readonly
                  />

                    <div class="help-block with-errors"></div>
                  </div>
                </div>
             
           
               
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Quantity</label>
               
                      {% render_field form.quantity  class="form-control" placeholder="Enter Quantity" id="product_quantity"  %}

                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Price *</label>
                    {% render_field form.price class="form-control" placeholder="Enter Price" id="product_price" %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label>Discount *</label>
                    {% render_field form.discount class="form-control" placeholder="Enter Price" id="product_price" %}
                    <div class="help-block with-errors"></div>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary mr-2">
                Add Product
              </button>
              <button type="reset" class="btn btn-danger">Reset</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Page end  -->
  </div>
</div>

{% endblock content %}

pos/templates/sales/list_sales.html
{% extends 'base/base.html' %} {% block content %}
<div class="wrapper">
  <div class="content-page">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div
            class="d-flex flex-wrap align-items-center justify-content-between mb-4"
          >
            <div>
              <h4 class="mb-3">Sale List</h4>
              <p class="mb-0">
                Sales of Today <b>{{ sales.count }}</b> Amount
                <b>{{todays_total_sales}}</b>
              </p>
            </div>
            <a href="page-add-sale.html" class="btn btn-primary add-list"
              ><i class="las la-plus mr-3"></i>Add Sale</a
            >
          </div>
        </div>
        <a href = "{% url 'products:export_all_sales_excel' %}">
          <div style="margin-left: 15px; display: flex; align-items: center; flex-direction: column;">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><defs><linearGradient id="vscodeIconsFileTypeExcel0" x1="4.494" x2="13.832" y1="-2092.086" y2="-2075.914" gradientTransform="translate(0 2100)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#18884f"/><stop offset=".5" stop-color="#117e43"/><stop offset="1" stop-color="#0b6631"/></linearGradient></defs><path fill="#185c37" d="M19.581 15.35L8.512 13.4v14.409A1.192 1.192 0 0 0 9.705 29h19.1A1.192 1.192 0 0 0 30 27.809V22.5Z"/><path fill="#21a366" d="M19.581 3H9.705a1.192 1.192 0 0 0-1.193 1.191V9.5L19.581 16l5.861 1.95L30 16V9.5Z"/><path fill="#107c41" d="M8.512 9.5h11.069V16H8.512Z"/><path d="M16.434 8.2H8.512v16.25h7.922a1.2 1.2 0 0 0 1.194-1.191V9.391A1.2 1.2 0 0 0 16.434 8.2Z" opacity=".1"/><path d="M15.783 8.85H8.512V25.1h7.271a1.2 1.2 0 0 0 1.194-1.191V10.041a1.2 1.2 0 0 0-1.194-1.191Z" opacity=".2"/><path d="M15.783 8.85H8.512V23.8h7.271a1.2 1.2 0 0 0 1.194-1.191V10.041a1.2 1.2 0 0 0-1.194-1.191Z" opacity=".2"/><path d="M15.132 8.85h-6.62V23.8h6.62a1.2 1.2 0 0 0 1.194-1.191V10.041a1.2 1.2 0 0 0-1.194-1.191Z" opacity=".2"/><path fill="url(#vscodeIconsFileTypeExcel0)" d="M3.194 8.85h11.938a1.193 1.193 0 0 1 1.194 1.191v11.918a1.193 1.193 0 0 1-1.194 1.191H3.194A1.192 1.192 0 0 1 2 21.959V10.041A1.192 1.192 0 0 1 3.194 8.85Z"/><path fill="#fff" d="m5.7 19.873l2.511-3.884l-2.3-3.862h1.847L9.013 14.6c.116.234.2.408.238.524h.017c.082-.188.169-.369.26-.546l1.342-2.447h1.7l-2.359 3.84l2.419 3.905h-1.809l-1.45-2.711A2.355 2.355 0 0 1 9.2 16.8h-.024a1.688 1.688 0 0 1-.168.351l-1.493 2.722Z"/><path fill="#33c481" d="M28.806 3h-9.225v6.5H30V4.191A1.192 1.192 0 0 0 28.806 3Z"/><path fill="#107c41" d="M19.581 16H30v6.5H19.581Z"/></svg>
          <p> Export to Excel</p>
          </div>
          </a>
        <div class="col-lg-12">
          <div class="table-responsive rounded mb-3">
            <table class="data-table table mb-0 tbl-server-info">
              <thead class="bg-white text-uppercase">
                <tr class="ligth ligth-data">
                  <th>
                    <div class="checkbox d-inline-block">
                      <input
                        type="checkbox"
                        class="checkbox-input"
                        id="checkbox1"
                      />
                      <label for="checkbox1" class="mb-0"></label>
                    </div>
                  </th>
                  <th>Date</th>
                  <th>Product Name</th>
                  <th>Quantity</th>
                  <th>Paid</th>
                  <th>profit</th>
                  <th>Biller</th>
                  <th>Discount</th>
                  <th>Stock Left</th>

                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody class="ligth-body">
                {% for sale in sales %}

                <tr>
                  <td>
                    <div class="checkbox d-inline-block">
                      <input
                        type="checkbox"
                        class="checkbox-input"
                        id="checkbox2"
                      />
                      <label for="checkbox2" class="mb-0"></label>
                    </div>
                  </td>
                  <td>{{ sale.date_sold }}</td>
                  <td>{{ sale.product.product_name }}</td>
                  <td>{{ sale.quantity }}</td>
                  <td>{{ sale.total }}</td>
                  <td>{{ sale.total_profit}} </td>
                  <td>{{ sale.user.username }}</td>
                  <td>{{ sale.discount }}</td>
                  <td>{{ sale.stock_left }}</td>
                  <td><div class="badge badge-success">Paid</div></td>

                  <td>
                    <div class="d-flex align-items-center list-action">
                      <a
                        class="badge badge-info mr-2"
                        data-toggle="tooltip"
                        data-placement="top"
                        title=""
                        data-original-title="View"
                        href="#"
                        ><i class="ri-eye-line mr-0"></i
                      ></a>
                      <a
                        class="badge bg-success mr-2"
                        data-toggle="tooltip"
                        data-placement="top"
                        title=""
                        data-original-title="Edit"
                        href="#"
                        ><i class="ri-pencil-line mr-0"></i
                      ></a>
                      <a
                        class="badge bg-warning mr-2"
                        data-toggle="tooltip"
                        data-placement="top"
                        title=""
                        data-original-title="Delete"
                        href="#"
                        ><i class="ri-delete-bin-line mr-0"></i
                      ></a>
                    </div>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- Page end  -->
    </div>
    <!-- Modal Edit -->
    <div
      class="modal fade"
      id="edit-note"
      tabindex="-1"
      role="dialog"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <div class="popup text-left">
              <div class="media align-items-top justify-content-between">
                <h3 class="mb-3">Product</h3>
                <div class="btn-cancel p-0" data-dismiss="modal">
                  <i class="las la-times"></i>
                </div>
              </div>
              <div class="content edit-notes">
                <div
                  class="card card-transparent card-block card-stretch event-note mb-0"
                >
                  <div class="card-body px-0 bukmark">
                    <div
                      class="d-flex align-items-center justify-content-between pb-2 mb-3 border-bottom"
                    >
                      <div class="quill-tool"></div>
                    </div>
                    <div id="quill-toolbar1">
                      <p>
                        Virtual Digital Marketing Course every week on Monday,
                        Wednesday and Saturday.Virtual Digital Marketing Course
                        every week on Monday
                      </p>
                    </div>
                  </div>
                  <div class="card-footer border-0">
                    <div
                      class="d-flex flex-wrap align-items-ceter justify-content-end"
                    >
                      <div class="btn btn-primary mr-3" data-dismiss="modal">
                        Cancel
                      </div>
                      <div class="btn btn-outline-primary" data-dismiss="modal">
                        Save
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

pos/templates/sales/receipt.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Receipt</title>
    <style>
      /* Add your custom CSS styles here */
      body {
        font-family: Arial, sans-serif;
        font-size: 14px;
      }
      .receipt {
        width: 300px;
        margin: 0 auto;
        text-align: center;
      }
      .header {
        font-size: 20px;
        font-weight: bold;
        margin-bottom: 10px;
      }
      table {
        width: 100%;
        margin-bottom: 10px;
      }
      th,
      td {
        padding: 5px;
        border: 1px solid black;
      }
      .footer {
        font-size: 16px;
        font-weight: bold;
        margin-top: 10px;
      }
    </style>
  </head>
  <body>
    <div id="invoice-POS">
      <center id="top">
        <div class="logo"></div>
        <div class="info">
          <h2>SBISTechs Inc</h2>
        </div>
        <!--End Info-->
      </center>
      <!--End InvoiceTop-->

      <div id="mid">
        <div class="info">
          <h2>Contact Info</h2>
          <p>
            Address : street city, state 0000<br />
            Email : JohnDoe@gmail.com<br />
            Phone : 555-555-5555<br />
          </p>
        </div>
      </div>
      <!--End Invoice Mid-->

      <div id="bot">
        <div id="table">
          <table>
            <tr class="tabletitle">
              <td class="item"><h2>Item</h2></td>
              <td class="Hours"><h2>Qty</h2></td>
              <td class="Rate"><h2>Rate</h2></td>
              <td class="subtotal"><h2>Subtotal</h2></td>
            </tr>

            <tr class="service">
              <td class="tableitem"><p class="itemtext">Communication</p></td>
              <td class="tableitem"><p class="itemtext">5</p></td>
              <td class="tableitem"><p class="itemtext">$75.00</p></td>
              <td class="tableitem"><p class="itemtext">$375.00</p></td>
            </tr>

            <tr class="service">
              <td class="tableitem"><p class="itemtext">Asset Gathering</p></td>
              <td class="tableitem"><p class="itemtext">3</p></td>
              <td class="tableitem"><p class="itemtext">$75.00</p></td>
              <td class="tableitem"><p class="itemtext">$225.00</p></td>
            </tr>

            <tr class="service">
              <td class="tableitem">
                <p class="itemtext">Design Development</p>
              </td>
              <td class="tableitem"><p class="itemtext">5</p></td>
              <td class="tableitem"><p class="itemtext">$75.00</p></td>
              <td class="tableitem"><p class="itemtext">$375.00</p></td>
            </tr>

            <tr class="service">
              <td class="tableitem"><p class="itemtext">Animation</p></td>
              <td class="tableitem"><p class="itemtext">20</p></td>
              <td class="tableitem"><p class="itemtext">$75.00</p></td>
              <td class="tableitem"><p class="itemtext">$1500.00</p></td>
            </tr>

            <tr class="discount">
              <td colspan="3" class="tableitem">
                <p class="itemtext">Discount (10%)</p>
              </td>
              <td class="tableitem"><p class="itemtext">-$247.50</p></td>
            </tr>

            <tr class="grandtotal">
              <td colspan="3" class="tableitem">
                <p class="itemtext">Grand Total</p>
              </td>
              <td class="tableitem"><p class="itemtext">$2227.50</p></td>
            </tr>
          </table>
        </div>
        <!--End Table-->

        <div id="legalcopy">
          <p class="legal">
            <strong>Thank you for your business!</strong><br />
            We appreciate your patronage and look forward to serving you again.
          </p>
        </div>
      </div>
      <!--End InvoiceBot-->
    </div>

    <script type="text/javascript">
        window.onload = function () {
          window.print();
      
          // Wait for the print dialog to close before redirecting
          var printTimeout = setTimeout(function() {
            window.location.href = "/list_sales";
          }, 1000); // Change the timeout value as needed
      
          // Cancel the redirect if the user cancels the print dialog
          window.onbeforeprint = function() {
            clearTimeout(printTimeout);
          };
        };
      </script>
    <!--End Invoice-->
  </body>
</html>