pos/api/urls.py
from django.urls import path
from .views import ProductsListApiView,ProductsUpdateView


app_name = "api"


urlpatterns = [
    path("products/", ProductsListApiView.as_view(), name="products"),
    path("products/update/<int:pk>", ProductsUpdateView.as_view(), name="products-update")
    ]

pos/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_select2 import urls as select2_urls


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("product.urls", namespace="products")),
    path("auth/", include("authentication.urls", namespace="authentication")),
    path("select2/", include(select2_urls), name="select2"),
]


urlpatterns += [path("api/", include("api.urls", namespace="api"))]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    

pos/product/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
from urllib.parse import urlencode
from django.urls import re_path


app_name = "products"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    # ? products
    path("product-list", views.ProductList.as_view(), name="product_list"),
    path("add-product", views.addproduct, name="add_product"),
    path("add_single_product", views.add_single_product, name="add_single_product"),
    path("upload_products", views.upload_products, name="upload_products"),
    path("list-category", views.list_category, name="list_category"),
    path("add_product_upload", views.add_product_upload, name="add_product_upload"),
    path("add-category", views.AddCategory, name="add_category"),
    # sales
    path("add_sales", views.AddSale.as_view(), name="add_sales"),
    path("list_sales", views.ListSale.as_view(), name="list_sales"),
    path("product_search", views.AddSale.as_view(), name="product_search"),
    path("complete_sale", csrf_exempt(views.complete_sale), name="complete_sale"),
    #! purchases
    path("add_purchases", views.AddPurchase.as_view(), name="add_purchases"),
    path("list_purchases", views.ListPurchase.as_view(), name="list_purchases"),
    path("add_purchase_upload", views.add_purchase_upload, name="add_purchase_upload"),
    path(
        "generate_purchase_list",
        views.generate_purchase_list,
        name="generate_purchase_list",
    ),
    path("add_single_purchase", views.add_single_purchase, name="add_single_purchase"),
    path("add_single_sell", views.add_single_sell, name="add_single_sell"),
    path("upload_purchase", views.upload_purchase, name="upload_purchase"),
    #!report
    path("reports", views.reports, name="reports"),
    # utils
    path("generate_barcode", views.generate_barcode, name="generate_barcode"),
    path(
        "get_product_by_uuid/<str:uuid>",
        views.get_product_by_uuid,
        name="get_product_by_uuid",
    ),
    # export to excel
    path("export_to_excel", views.export_to_excel, name="export_to_excel"),
    path(
        "export_all_products_excel",
        views.export_all_products_excel,
        name="export_all_products_excel",
    ),
    path(
        "export_all_sales_excel",
        views.export_all_sales_excel,
        name="export_all_sales_excel",
    ),
    path(
        "get_single_product/<str:pk>/",
        views.get_single_product,
        name="update_product",
    ),path("daily_profit", views.daily_profit, name="daily_profit"),
    path("month_profit", views.get_month_profit, name="month_profit"),
]

# htmx

urlpatterns += [
    # path(
    #     "get_single_product/<str:pk>/",
    #     views.get_single_product,
    #     name="update_product",
    # ),
    re_path(
        "get_profit_for_single_date/<str:date>",
        views.get_profit_for_single_date,
        name="get_profit_for_date",
    ),
]

pos/templates/dashboard/Rightmenu.html
{% load static %}

<div class="iq-sidebar sidebar-default">
  <div
    class="iq-sidebar-logo d-flex align-items-center justify-content-between"
  >
    <a href="{%url 'products:dashboard' %}" class="header-logo">
      <img
        src="{% static 'images/logo.png' %}"
        class="img-fluid rounded-normal light-logo"
        alt="logo"
      />
      <h5 class="logo-title light-logo ml-3">POSDash</h5>
    </a>
    <div class="iq-menu-bt-sidebar ml-0">
      <i class="las la-bars wrapper-menu">
        <svg
          class="svg-icon"
          id="menu-icon"
          width="20"
          height="20"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
        >
          <path
            d="M2,18 L22,18 M2,12 L22,12 M2,6 L22,6"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </i>
    </div>
  </div>
  <div class="data-scrollbar" data-scroll="1">
    <nav class="iq-sidebar-menu">
      <ul id="iq-sidebar-toggle" class="iq-menu">
        {% if request.user.is_superuser and request.user.is_authenticated %}
        <li class="active">
          <a href="{%url 'products:dashboard' %}" class="svg-icon">
            <svg
              class="svg-icon"
              id="p-dash1"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path
                d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"
              ></path>
              <polyline points="3.27 6.96 12 12.01 20.73 6.96"></polyline>
              <line x1="12" y1="22.08" x2="12" y2="12"></line>
            </svg>
            <span class="ml-4">Dashboards</span>
          </a>
        </li>
        <li class=" ">
          <a
            href="#product"
            class="collapsed"
            data-toggle="collapse"
            aria-expanded="false"
          >
            <svg
              class="svg-icon"
              id="p-dash2"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <circle cx="9" cy="21" r="1"></circle>
              <circle cx="20" cy="21" r="1"></circle>
              <path
                d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"
              ></path>
            </svg>
            <span class="ml-4">Products</span>
            <svg
              class="svg-icon iq-arrow-right arrow-active"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="10 15 15 20 20 15"></polyline>
              <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
            </svg>
          </a>
          <ul
            id="product"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          >
            <li class="">
              <a href="{% url 'products:product_list' %}">
                <i class="las la-minus"></i><span>List Product</span>
              </a>
            </li>
            <li class="">
              <a href="{% url 'products:add_product' %}">
                <i class="las la-minus"></i><span>Add Product</span>
              </a>
            </li>
          </ul>
        </li>
        <li class=" ">
          <a
            href="#category"
            class="collapsed"
            data-toggle="collapse"
            aria-expanded="false"
          >
            <svg
              class="svg-icon"
              id="p-dash3"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect>
              <path
                d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"
              ></path>
            </svg>
            <span class="ml-4">Categories</span>
            <svg
              class="svg-icon iq-arrow-right arrow-active"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="10 15 15 20 20 15"></polyline>
              <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
            </svg>
          </a>
          <ul
            id="category"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          >
            <li class="">
              <a href="{% url 'products:list_category' %}">
                <i class="las la-minus"></i><span>List Category</span>
              </a>
            </li>
            <li class="">
              <a href="{% url 'products:add_category' %}">
                <i class="las la-minus"></i><span>Add Category</span>
              </a>
            </li>
          </ul>
        </li>
        <li class=" ">
          <a
            href="#purchase"
            class="collapsed"
            data-toggle="collapse"
            aria-expanded="false"
          >
            <svg
              class="svg-icon"
              id="p-dash5"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
              <line x1="1" y1="10" x2="23" y2="10"></line>
            </svg>
            <span class="ml-4">Purchases</span>
            <svg
              class="svg-icon iq-arrow-right arrow-active"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="10 15 15 20 20 15"></polyline>
              <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
            </svg>
          </a>
          <ul
            id="purchase"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          >
            <li class="">
              <a href="{% url 'products:list_purchases' %}">
                <i class="las la-minus"></i><span>List Purchases</span>
              </a>
            </li>
            <li class="">
              <a href="{% url 'products:add_purchases' %}">
                <i class="las la-minus"></i><span>Add purchase</span>
              </a>
            </li>
            <li class="">
              <a href="{% url 'products:generate_purchase_list' %}">
                <i class="las la-minus"></i><span>Generate Purchase List</span>
              </a>
            </li>
          </ul>
        </li>
        <li class=" ">
          <a
            href="#return"
            class="collapsed"
            data-toggle="collapse"
            aria-expanded="false"
          >
            <svg
              class="svg-icon"
              id="p-dash6"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="4 14 10 14 10 20"></polyline>
              <polyline points="20 10 14 10 14 4"></polyline>
              <line x1="14" y1="10" x2="21" y2="3"></line>
              <line x1="3" y1="21" x2="10" y2="14"></line>
            </svg>
            <span class="ml-4">Returns</span>
            <svg
              class="svg-icon iq-arrow-right arrow-active"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="10 15 15 20 20 15"></polyline>
              <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
            </svg>
          </a>
          <ul
            id="return"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          >
            <li class="">
              <a href="{% url 'products:month_profit' %}">
                <i class="las la-minus"></i><span>Month Profit</span>
              </a>
            </li>
            <li class="">
              <a href="{% url 'products:daily_profit' %}">
                <i class="las la-minus"></i><span>Daily Profit</span>
              </a>
            </li>
          </ul>
        </li>

        <li class="">
          <a href="{% url 'products:reports' %}" class="">
            <svg
              class="svg-icon"
              id="p-dash7"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path
                d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"
              ></path>
              <polyline points="14 2 14 8 20 8"></polyline>
              <line x1="16" y1="13" x2="8" y2="13"></line>
              <line x1="16" y1="17" x2="8" y2="17"></line>
              <polyline points="10 9 9 9 8 9"></polyline>
            </svg>
            <span class="ml-4">Reports</span>
          </a>
          <ul
            id="reports"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          ></ul>
        </li>
        {% endif %}
        <li class=" ">
          <a
            href="#sale"
            class="collapsed"
            data-toggle="collapse"
            aria-expanded="false"
          >
            <svg
              class="svg-icon"
              id="p-dash4"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path>
              <path d="M22 12A10 10 0 0 0 12 2v10z"></path>
            </svg>
            <span class="ml-4">Sale</span>
            <svg
              class="svg-icon iq-arrow-right arrow-active"
              width="20"
              height="20"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <polyline points="10 15 15 20 20 15"></polyline>
              <path d="M4 4h7a4 4 0 0 1 4 4v12"></path>
            </svg>
          </a>
          <ul
            id="sale"
            class="iq-submenu collapse"
            data-parent="#iq-sidebar-toggle"
          >
            <li class="">
              <a href="{% url 'products:list_sales'%}">
                <i class="las la-minus"></i><span>List Sale</span>
              </a>
            </li>
            <li class="">
              <a href="/add_sales?#" id="add_sales_link">
                <i class="las la-minus"></i><span>Add Sale</span>
              </a>
            </li>
            <li class="">
              <a
                href="{% url 'products:add_single_sell' %}"
                id="add_sales_link"
              >
                <i class="las la-minus"></i><span>Add Single Sale</span>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>

    <div class="p-3"></div>
  </div>
</div>